package momanii.hani.supernova_emoji;

import java.util.ArrayList;
import java.util.List;

import hani.momanii.supernova_emoji_library.Helper.EmojiPackage;
import hani.momanii.supernova_emoji_library.Models.Emoji;

public class Emojis {

    static List<EmojiPackage> getEmojiPackages() {
        List<EmojiPackage> emojiPackages = new ArrayList<>();
        //emojiPackages.add(new EmojiPackage(PEOPLE, R.drawable.selector_emoji_people));
        emojiPackages.add(new EmojiPackage(CUSTOME, R.drawable.selector_emoji_activity));
        return emojiPackages;
    }

    private static final Emoji[] CUSTOME = new Emoji[] {
            new Emoji(R.drawable.emoji_1f999, 0x1f999),
            new Emoji(R.drawable.emoji_1f660, 0x1f660)
    };

    /*private static final Emojicon[] PEOPLE = new Emojicon[]{
            Emojicon.fromCodePoint(0x1f600),
            Emojicon.fromCodePoint(0x1f62c),
            Emojicon.fromCodePoint(0x1f601),
            Emojicon.fromCodePoint(0x1f602),
            Emojicon.fromCodePoint(0x1f603),
            Emojicon.fromCodePoint(0x1f604),
            Emojicon.fromCodePoint(0x1f605),
            Emojicon.fromCodePoint(0x1f606),
            Emojicon.fromCodePoint(0x1f607),
            Emojicon.fromCodePoint(0x1f609),
            Emojicon.fromCodePoint(0x1f60a),
            Emojicon.fromCodePoint(0x1f642),
            Emojicon.fromCodePoint(0x1f643),
            Emojicon.fromChar((char)0x263a),
            Emojicon.fromCodePoint(0x1f60b),
            Emojicon.fromCodePoint(0x1f60c),
            Emojicon.fromCodePoint(0x1f60d),
            Emojicon.fromCodePoint(0x1f618),
            Emojicon.fromCodePoint(0x1f617),
            Emojicon.fromCodePoint(0x1f619),
            Emojicon.fromCodePoint(0x1f61a),
            Emojicon.fromCodePoint(0x1f61c),
            Emojicon.fromCodePoint(0x1f61d),
            Emojicon.fromCodePoint(0x1f61b),
            Emojicon.fromCodePoint(0x1f911),
            Emojicon.fromCodePoint(0x1f913),
            Emojicon.fromCodePoint(0x1f60e),
            Emojicon.fromCodePoint(0x1f917),
            Emojicon.fromCodePoint(0x1f60f),
            Emojicon.fromCodePoint(0x1f636),
            Emojicon.fromCodePoint(0x1f610),
            Emojicon.fromCodePoint(0x1f611),
            Emojicon.fromCodePoint(0x1f612),
            Emojicon.fromCodePoint(0x1f644),
            Emojicon.fromCodePoint(0x1f914),
            Emojicon.fromCodePoint(0x1f633),
            Emojicon.fromCodePoint(0x1f61e),
            Emojicon.fromCodePoint(0x1f61f),
            Emojicon.fromCodePoint(0x1f620),
            Emojicon.fromCodePoint(0x1f621),
            Emojicon.fromCodePoint(0x1f614),
            Emojicon.fromCodePoint(0x1f615),
            Emojicon.fromCodePoint(0x1f641),
            Emojicon.fromChar((char)0x2639),
            Emojicon.fromCodePoint(0x1f623),
            Emojicon.fromCodePoint(0x1f616),
            Emojicon.fromCodePoint(0x1f62b),
            Emojicon.fromCodePoint(0x1f629),
            Emojicon.fromCodePoint(0x1f624),
            Emojicon.fromCodePoint(0x1f62e),
            Emojicon.fromCodePoint(0x1f631),
            Emojicon.fromCodePoint(0x1f628),
            Emojicon.fromCodePoint(0x1f630),
            Emojicon.fromCodePoint(0x1f62f),
            Emojicon.fromCodePoint(0x1f626),
            Emojicon.fromCodePoint(0x1f627),
            Emojicon.fromCodePoint(0x1f622),
            Emojicon.fromCodePoint(0x1f625),
            Emojicon.fromCodePoint(0x1f62a),
            Emojicon.fromCodePoint(0x1f613),
            Emojicon.fromCodePoint(0x1f62d),
            Emojicon.fromCodePoint(0x1f635),
            Emojicon.fromCodePoint(0x1f632),
            Emojicon.fromCodePoint(0x1f910),
            Emojicon.fromCodePoint(0x1f637),
            Emojicon.fromCodePoint(0x1f912),
            Emojicon.fromCodePoint(0x1f915),
            Emojicon.fromCodePoint(0x1f634),
            Emojicon.fromCodePoint(0x1f4a4),
            Emojicon.fromCodePoint(0x1f4a9),
            Emojicon.fromCodePoint(0x1f608),
            Emojicon.fromCodePoint(0x1f47f),
            Emojicon.fromCodePoint(0x1f479),
            Emojicon.fromCodePoint(0x1f47a),
            Emojicon.fromCodePoint(0x1f480),
            Emojicon.fromCodePoint(0x1f47b),
            Emojicon.fromCodePoint(0x1f47d),
            Emojicon.fromCodePoint(0x1f916),
            Emojicon.fromCodePoint(0x1f63a),
            Emojicon.fromCodePoint(0x1f638),
            Emojicon.fromCodePoint(0x1f639),
            Emojicon.fromCodePoint(0x1f63b),
            Emojicon.fromCodePoint(0x1f63c),
            Emojicon.fromCodePoint(0x1f63d),
            Emojicon.fromCodePoint(0x1f640),
            Emojicon.fromCodePoint(0x1f63f),
            Emojicon.fromCodePoint(0x1f63e),
            Emojicon.fromCodePoint(0x1f64c),
            Emojicon.fromCodePoint(0x1f44f),
            Emojicon.fromCodePoint(0x1f44b),
            Emojicon.fromCodePoint(0x1f44d),
            Emojicon.fromCodePoint(0x1f44e),
            Emojicon.fromCodePoint(0x1f44a),
            Emojicon.fromChar((char)0x270a),
            Emojicon.fromChar((char)0x270c),
            Emojicon.fromCodePoint(0x1f44c),
            Emojicon.fromChar((char)0x270b),
            Emojicon.fromCodePoint(0x1f450),
            Emojicon.fromCodePoint(0x1f4aa),
            Emojicon.fromCodePoint(0x1f64f),
            Emojicon.fromChar((char)0x261d),
            Emojicon.fromCodePoint(0x1f446),
            Emojicon.fromCodePoint(0x1f447),
            Emojicon.fromCodePoint(0x1f448),
            Emojicon.fromCodePoint(0x1f449),
            Emojicon.fromCodePoint(0x1f595),
            Emojicon.fromCodePoint(0x1f590),
            Emojicon.fromCodePoint(0x1f918),
            Emojicon.fromChar((char)0x270d),
            Emojicon.fromCodePoint(0x1f485),
            Emojicon.fromCodePoint(0x1f444),
            Emojicon.fromCodePoint(0x1f445),
            Emojicon.fromCodePoint(0x1f442),
            Emojicon.fromCodePoint(0x1f443),
            Emojicon.fromCodePoint(0x1f441),
            Emojicon.fromCodePoint(0x1f440),
            Emojicon.fromCodePoint(0x1f464),
            Emojicon.fromCodePoint(0x1f465),
            Emojicon.fromCodePoint(0x1f5e3),
            Emojicon.fromCodePoint(0x1f476),
            Emojicon.fromCodePoint(0x1f466),
            Emojicon.fromCodePoint(0x1f467),
            Emojicon.fromCodePoint(0x1f468),
            Emojicon.fromCodePoint(0x1f469),
            Emojicon.fromCodePoint(0x1f471),
            Emojicon.fromCodePoint(0x1f474),
            Emojicon.fromCodePoint(0x1f475),
            Emojicon.fromCodePoint(0x1f472),
            Emojicon.fromCodePoint(0x1f473),
            Emojicon.fromCodePoint(0x1f46e),
            Emojicon.fromCodePoint(0x1f477),
            Emojicon.fromCodePoint(0x1f482),
            Emojicon.fromCodePoint(0x1f575),
            Emojicon.fromCodePoint(0x1f385),
            Emojicon.fromCodePoint(0x1f47c),
            Emojicon.fromCodePoint(0x1f478),
            Emojicon.fromCodePoint(0x1f470),
            Emojicon.fromCodePoint(0x1f6b6),
            Emojicon.fromCodePoint(0x1f3c3),
            Emojicon.fromCodePoint(0x1f483),
            Emojicon.fromCodePoint(0x1f46f),
            Emojicon.fromCodePoint(0x1f525),
            Emojicon.fromChar((char)0x2728),
            Emojicon.fromCodePoint(0x1f31f),
            Emojicon.fromCodePoint(0x1f4ab),
            Emojicon.fromCodePoint(0x1f4a2),
            Emojicon.fromCodePoint(0x1f46b),
            Emojicon.fromCodePoint(0x1f46c),
            Emojicon.fromCodePoint(0x1f46d),
            Emojicon.fromCodePoint(0x1f647),
            Emojicon.fromCodePoint(0x1f481),
            Emojicon.fromCodePoint(0x1f645),
            Emojicon.fromCodePoint(0x1f646),
            Emojicon.fromCodePoint(0x1f64b),
            Emojicon.fromCodePoint(0x1f64e),
            Emojicon.fromCodePoint(0x1f64d),
            Emojicon.fromCodePoint(0x1f487),
            Emojicon.fromCodePoint(0x1f486),
            Emojicon.fromCodePoint(0x1f491),
            Emojicon.fromCodePoint(0x1f48f),
            Emojicon.fromCodePoint(0x1f46a),
            Emojicon.fromCodePoint(0x1f45a),
            Emojicon.fromCodePoint(0x1f455),
            Emojicon.fromCodePoint(0x1f456),
            Emojicon.fromCodePoint(0x1f454),
            Emojicon.fromCodePoint(0x1f457),
            Emojicon.fromCodePoint(0x1f459),
            Emojicon.fromCodePoint(0x1f458),
            Emojicon.fromCodePoint(0x1f484),
            Emojicon.fromCodePoint(0x1f48b),
            Emojicon.fromCodePoint(0x1f463),
            Emojicon.fromCodePoint(0x1f460),
            Emojicon.fromCodePoint(0x1f461),
            Emojicon.fromCodePoint(0x1f462),
            Emojicon.fromCodePoint(0x1f45e),
            Emojicon.fromCodePoint(0x1f45f),
            Emojicon.fromCodePoint(0x1f452),
            Emojicon.fromCodePoint(0x1f3a9),
            Emojicon.fromCodePoint(0x1f393),
            Emojicon.fromCodePoint(0x1f451),
            Emojicon.fromChar((char)0x26d1),
            Emojicon.fromChar((char)0xe43a),
            Emojicon.fromCodePoint(0x1f45d),
            Emojicon.fromCodePoint(0x1f45b),
            Emojicon.fromCodePoint(0x1f45c),
            Emojicon.fromCodePoint(0x1f4bc),
            Emojicon.fromCodePoint(0x1f453),
            Emojicon.fromCodePoint(0x1f576),
            Emojicon.fromCodePoint(0x1f48d),
            Emojicon.fromCodePoint(0x1f302),
    };*/

    /*public static Emojicon[] getEmojicons(Emoji[] emojis) {
        Emojicon[] emojicons = new Emojicon[emojis.length];
        for (int i = 0; i < emojis.length; i++) {
            emojicons[i] = Emojicon.fromDrawable(emojis[i].getName(), emojis[i].getDrawable());
        }
        return emojicons;
    }

    private static final Emoji[] PEOPLE = new Emoji[]{
            new Emoji(R.drawable.emoji_1f6600, "1f6600")
    };

    private static final Emojicon[] PEOPLE2 = new Emojicon[]{
            Emojicon.fromDrawable("1f607", hani.momanii.supernova_emoji_library.R.drawable.emoji_1f607)
    };*/

    /*private static final Emojicon[] PEOPLE = new Emojicon[]{
        Emojicon.fromDrawable(0x1f600, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f600),
        Emojicon.fromDrawable(0x1f62c, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f62c),
        Emojicon.fromDrawable(0x1f601, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f601),
        Emojicon.fromDrawable(0x1f602, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f602),
        Emojicon.fromDrawable(0x1f603, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f603),
        Emojicon.fromDrawable(0x1f604, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f604),
        Emojicon.fromDrawable(0x1f605, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f605),
        Emojicon.fromDrawable(0x1f606, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f606),
        Emojicon.fromDrawable(0x1f607, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f607),
        Emojicon.fromDrawable(0x1f609, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f609),
        Emojicon.fromDrawable(0x1f60a, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f60a),
        Emojicon.fromDrawable(0x1f642, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f642),
        Emojicon.fromDrawable(0x1f643, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f643),
        Emojicon.fromDrawable(0x263a, hani.momanii.supernova_emoji_library.R.drawable.emoji_263a),
        Emojicon.fromDrawable(0x1f60b, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f60b),
        Emojicon.fromDrawable(0x1f60c, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f60c),
        Emojicon.fromDrawable(0x1f60d, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f60d),
        Emojicon.fromDrawable(0x1f618, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f618),
        Emojicon.fromDrawable(0x1f617, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f617),
        Emojicon.fromDrawable(0x1f619, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f619),
        Emojicon.fromDrawable(0x1f61a, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f61a),
        Emojicon.fromDrawable(0x1f61c, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f61c),
        Emojicon.fromDrawable(0x1f61d, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f61d),
        Emojicon.fromDrawable(0x1f61b, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f61b),
        Emojicon.fromDrawable(0x1f911, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f911),
        Emojicon.fromDrawable(0x1f913, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f913),
        Emojicon.fromDrawable(0x1f60e, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f60e),
        Emojicon.fromDrawable(0x1f917, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f917),
        Emojicon.fromDrawable(0x1f60f, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f60f),
        Emojicon.fromDrawable(0x1f636, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f636),
        Emojicon.fromDrawable(0x1f610, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f610),
        Emojicon.fromDrawable(0x1f611, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f611),
        Emojicon.fromDrawable(0x1f612, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f612),
        Emojicon.fromDrawable(0x1f644, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f644),
        Emojicon.fromDrawable(0x1f914, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f914),
        Emojicon.fromDrawable(0x1f633, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f633),
        Emojicon.fromDrawable(0x1f61e, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f61e),
        Emojicon.fromDrawable(0x1f61f, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f61f),
        Emojicon.fromDrawable(0x1f620, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f620),
        Emojicon.fromDrawable(0x1f621, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f621),
        Emojicon.fromDrawable(0x1f614, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f614),
        Emojicon.fromDrawable(0x1f615, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f615),
        Emojicon.fromDrawable(0x1f641, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f641),
        Emojicon.fromDrawable(0x2639, hani.momanii.supernova_emoji_library.R.drawable.emoji_2639),
        Emojicon.fromDrawable(0x1f623, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f623),
        Emojicon.fromDrawable(0x1f616, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f616),
        Emojicon.fromDrawable(0x1f62b, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f62b),
        Emojicon.fromDrawable(0x1f629, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f629),
        Emojicon.fromDrawable(0x1f624, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f624),
        Emojicon.fromDrawable(0x1f62e, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f62e),
        Emojicon.fromDrawable(0x1f631, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f631),
        Emojicon.fromDrawable(0x1f628, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f628),
        Emojicon.fromDrawable(0x1f630, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f630),
        Emojicon.fromDrawable(0x1f62f, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f62f),
        Emojicon.fromDrawable(0x1f626, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f626),
        Emojicon.fromDrawable(0x1f627, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f627),
        Emojicon.fromDrawable(0x1f622, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f622),
        Emojicon.fromDrawable(0x1f625, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f625),
        Emojicon.fromDrawable(0x1f62a, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f62a),
        Emojicon.fromDrawable(0x1f613, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f613),
        Emojicon.fromDrawable(0x1f62d, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f62d),
        Emojicon.fromDrawable(0x1f635, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f635),
        Emojicon.fromDrawable(0x1f632, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f632),
        Emojicon.fromDrawable(0x1f910, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f910),
        Emojicon.fromDrawable(0x1f637, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f637),
        Emojicon.fromDrawable(0x1f912, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f912),
        Emojicon.fromDrawable(0x1f915, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f915),
        Emojicon.fromDrawable(0x1f634, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f634),
        Emojicon.fromDrawable(0x1f4a4, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f4a4),
        Emojicon.fromDrawable(0x1f4a9, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f4a9),
        Emojicon.fromDrawable(0x1f608, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f608),
        Emojicon.fromDrawable(0x1f47f, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f47f),
        Emojicon.fromDrawable(0x1f479, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f479),
        Emojicon.fromDrawable(0x1f47a, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f47a),
        Emojicon.fromDrawable(0x1f480, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f480),
        Emojicon.fromDrawable(0x1f47b, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f47b),
        Emojicon.fromDrawable(0x1f47d, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f47d),
        Emojicon.fromDrawable(0x1f916, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f916),
        Emojicon.fromDrawable(0x1f63a, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f63a),
        Emojicon.fromDrawable(0x1f638, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f638),
        Emojicon.fromDrawable(0x1f639, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f639),
        Emojicon.fromDrawable(0x1f63b, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f63b),
        Emojicon.fromDrawable(0x1f63c, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f63c),
        Emojicon.fromDrawable(0x1f63d, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f63d),
        Emojicon.fromDrawable(0x1f640, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f640),
        Emojicon.fromDrawable(0x1f63f, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f63f),
        Emojicon.fromDrawable(0x1f63e, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f63e),
        Emojicon.fromDrawable(0x1f64c, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f64c_1f3fb),
        Emojicon.fromDrawable(0x1f44f, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f44f_1f3fb),
        Emojicon.fromDrawable(0x1f44b, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f44b_1f3fb),
        Emojicon.fromDrawable(0x1f44d, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f44d_1f3fb),
        Emojicon.fromDrawable(0x1f44e, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f44e_1f3fb),
        Emojicon.fromDrawable(0x1f44a, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f44a_1f3fb),
        Emojicon.fromDrawable(0x270a, hani.momanii.supernova_emoji_library.R.drawable.emoji_270a_1f3fb),
        Emojicon.fromDrawable(0x270c, hani.momanii.supernova_emoji_library.R.drawable.emoji_270c_1f3fb),
        Emojicon.fromDrawable(0x1f44c, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f44c_1f3fb),
        Emojicon.fromDrawable(0x270b, hani.momanii.supernova_emoji_library.R.drawable.emoji_270b_1f3fb),
        Emojicon.fromDrawable(0x1f450, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f450_1f3fb),
        Emojicon.fromDrawable(0x1f4aa, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f4aa_1f3fb),
        Emojicon.fromDrawable(0x1f64f, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f64f_1f3fb),
        Emojicon.fromDrawable(0x261d, hani.momanii.supernova_emoji_library.R.drawable.emoji_261d_1f3fb),
        Emojicon.fromDrawable(0x1f446, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f446_1f3fb),
        Emojicon.fromDrawable(0x1f447, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f447_1f3fb),
        Emojicon.fromDrawable(0x1f448, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f448_1f3fb),
        Emojicon.fromDrawable(0x1f449, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f449_1f3fb),
        Emojicon.fromDrawable(0x1f595, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f595_1f3fb),
        Emojicon.fromDrawable(0x1f590, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f590_1f3fb),
        Emojicon.fromDrawable(0x1f918, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f918_1f3fb),
        Emojicon.fromDrawable(0x270d, hani.momanii.supernova_emoji_library.R.drawable.emoji_270d_1f3fb),
        Emojicon.fromDrawable(0x1f485, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f485_1f3fb),
        Emojicon.fromDrawable(0x1f444, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f444),
        Emojicon.fromDrawable(0x1f445, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f445),
        Emojicon.fromDrawable(0x1f442, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f442_1f3fb),
        Emojicon.fromDrawable(0x1f443, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f443_1f3fb),
        Emojicon.fromDrawable(0x1f441, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f441),
        Emojicon.fromDrawable(0x1f440, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f440),
        Emojicon.fromDrawable(0x1f464, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f464),
        Emojicon.fromDrawable(0x1f465, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f465),
        Emojicon.fromDrawable(0x1f5e3, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f5e3),
        Emojicon.fromDrawable(0x1f476, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f476_1f3fb),
        Emojicon.fromDrawable(0x1f466, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f466_1f3fb),
        Emojicon.fromDrawable(0x1f467, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f467_1f3fb),
        Emojicon.fromDrawable(0x1f468, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f468_1f3fb),
        Emojicon.fromDrawable(0x1f469, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f469_1f3fb),
        Emojicon.fromDrawable(0x1f471, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f471_1f3fb),
        Emojicon.fromDrawable(0x1f474, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f474_1f3fb),
        Emojicon.fromDrawable(0x1f475, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f475_1f3fb),
        Emojicon.fromDrawable(0x1f472, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f472_1f3fb),
        Emojicon.fromDrawable(0x1f473, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f473_1f3fb),
        Emojicon.fromDrawable(0x1f46e, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f46e_1f3fb),
        Emojicon.fromDrawable(0x1f477, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f477_1f3fb),
        Emojicon.fromDrawable(0x1f482, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f482_1f3fb),
        Emojicon.fromDrawable(0x1f575, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f575),
        Emojicon.fromDrawable(0x1f385, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f385_1f3fb),
        Emojicon.fromDrawable(0x1f47c, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f47c_1f3fb),
        Emojicon.fromDrawable(0x1f478, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f478_1f3fb),
        Emojicon.fromDrawable(0x1f470, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f470_1f3fb),
        Emojicon.fromDrawable(0x1f6b6, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f6b6_1f3fb),
        Emojicon.fromDrawable(0x1f3c3, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f3c3_1f3fb),
        Emojicon.fromDrawable(0x1f483, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f483_1f3fb),
        Emojicon.fromDrawable(0x1f46f, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f46f),
        Emojicon.fromDrawable(0x2728, hani.momanii.supernova_emoji_library.R.drawable.emoji_2728),
        Emojicon.fromDrawable(0x1f31f, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f31f),
        Emojicon.fromDrawable(0x1f4ab, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f4ab),
        Emojicon.fromDrawable(0x1f4a2, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f4a2),

        Emojicon.fromDrawable(0x1f46b, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f46b),
        Emojicon.fromDrawable(0x1f46c, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f46c),
        Emojicon.fromDrawable(0x1f46d, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f46d),
        Emojicon.fromDrawable(0x1f647, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f647_1f3fb),
        Emojicon.fromDrawable(0x1f481, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f481_1f3fb),
        Emojicon.fromDrawable(0x1f645, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f645_1f3fb),
        Emojicon.fromDrawable(0x1f646, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f646_1f3fb),
        Emojicon.fromDrawable(0x1f64b, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f64b_1f3fb),
        Emojicon.fromDrawable(0x1f64e, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f64e_1f3fb),
        Emojicon.fromDrawable(0x1f64d, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f64d_1f3fb),
        Emojicon.fromDrawable(0x1f487, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f487_1f3fb),
        Emojicon.fromDrawable(0x1f486, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f486_1f3fb),
        Emojicon.fromDrawable(0x1f491, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f491),
        Emojicon.fromDrawable(0x1f48f, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f48f),
        Emojicon.fromDrawable(0x1f46a, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f46a),
        Emojicon.fromDrawable(0x1f45a, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f45a),
        Emojicon.fromDrawable(0x1f455, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f455),
        Emojicon.fromDrawable(0x1f456, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f456),
        Emojicon.fromDrawable(0x1f454, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f454),
        Emojicon.fromDrawable(0x1f457, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f457),
        Emojicon.fromDrawable(0x1f459, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f459),
        Emojicon.fromDrawable(0x1f458, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f458),
        Emojicon.fromDrawable(0x1f484, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f484),
        Emojicon.fromDrawable(0x1f48b, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f48b),
        Emojicon.fromDrawable(0x1f463, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f463),
        Emojicon.fromDrawable(0x1f460, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f460),
        Emojicon.fromDrawable(0x1f461, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f461),
        Emojicon.fromDrawable(0x1f462, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f462),
        Emojicon.fromDrawable(0x1f45e, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f45e),
        Emojicon.fromDrawable(0x1f45f, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f45f),
        Emojicon.fromDrawable(0x1f452, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f452),
        Emojicon.fromDrawable(0x1f3a9, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f3a9),
        Emojicon.fromDrawable(0x1f393, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f393),
        Emojicon.fromDrawable(0x1f451, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f451),
        Emojicon.fromDrawable(0x26d1, hani.momanii.supernova_emoji_library.R.drawable.emoji_26d1),
        Emojicon.fromDrawable(0xe43a, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f392),
        Emojicon.fromDrawable(0x1f45d, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f45d),
        Emojicon.fromDrawable(0x1f45b, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f45b),
        Emojicon.fromDrawable(0x1f45c, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f45c),
        Emojicon.fromDrawable(0x1f4bc, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f4bc),
        Emojicon.fromDrawable(0x1f453, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f453),
        Emojicon.fromDrawable(0x1f576, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f576),
        Emojicon.fromDrawable(0x1f48d, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f48d),
        Emojicon.fromDrawable(0x1f302, hani.momanii.supernova_emoji_library.R.drawable.emoji_1f302)
    };*/

}
